### ISSUE TITLE
el formulario de contacto no funciona

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/asoc#11]
https://ac.python.org.ar/#contacto

(tal vez podemos usar un google form??)

**Comment by edvm** [comment]
Es buena la de usar un google form. Si no se quiere usar google form, otra opción es:
1- Usar https://www.emailjs.com/ o algun tipo de servicio similar

**Comment by gilgamezh** [comment]
your call :-)

**Comment by pyojo** [comment]
#13

**Comment by edvm** [comment]
Fixed by @pyojo , muchas gracias!
Cierro el issue.
