### ISSUE TITLE
Necesitamos un código de conducta general

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc#12]
Algo como [esto](http://www.pycon.com.ar/codigo-de-conducta.html), pero "generalizado", que no sea específico para una conferencia (hay que re-redactarlo un poquito)

**Comment by edvm** [comment]
@facundobatista pasame el texto ( @reingart podes dar una mano? ), y lo agregamos al sitio :+1:

**Comment by reingart** [comment]
@edvm ya estaría el documento borrador: https://docs.google.com/document/d/1vrn5gM2W64vqmPiFdMz2MUA7Tttz32Rl1aolGtXyHdo/edit?usp=sharing

A lo que se había adelantado por Telegram, se agregó sección introductoria "Diversidad", "Información de Contacto", etc. (similares a lso usuados en PyConAr 2012), junto con cambios menores.

**Comment by edvm** [comment]
Perfecto @reingart @facundobatista cierro este issue y abro uno para meterlo en la web de la asoc, gracias! :+1:

**Comment by facundobatista** [comment]
Este issue *era* para meterlo en la web de la asoc...

**Comment by edvm** [comment]
Subido!
