### ISSUE TITLE
Issue Github

### ISSUE THREAD

**Issue by tdelgio** [PyAr/asoc#23]

**Comment by facundobatista** [comment]
?

**Comment by tdelgio** [comment]
Hola Facundo, mi nombre es Tomás
Investigando acerca de Python llegue a la Asociación

**Comment by tdelgio** [comment]
Hace unos años empecé a aprender python y me desvié del camino. Hoy quiero retomarlo y me gustaría colaborar como socio Arreglando/fixeando ya que soy principiante. 
No se si tenía que presentarme por este medio pero aprovecho para compartir el objetivo de mi asociación.

**Comment by facundobatista** [comment]
Hola Tomás! Estoy un poco perdido... ¿vos llenaste el form para ser socio de la Asoc Civil Python Argentina?

Gracias, saludos,
