### ISSUE TITLE
Propuesta con grillas

### ISSUE THREAD

**Issue by deimidis** [PyAr/asoc#7]
Estoy armando el cambio para la parte de la Comisión directiva. Así se vería en diferentes resoluciones
![com_pantalla_grande](https://user-images.githubusercontent.com/507068/32951328-6d284128-cba1-11e7-910c-d6d2adfd2d2d.png)
![com_pantalla_media](https://user-images.githubusercontent.com/507068/32951329-6d4ecdd4-cba1-11e7-9806-55ace237ae5e.png)
![com_pantalla_peq](https://user-images.githubusercontent.com/507068/32951330-6d72324c-cba1-11e7-9381-701ba7cc6828.png)

Por ahora no lo subí, a ver si es lo que más o menos esperan

**Comment by deimidis** [comment]
La imagen de Mariano es muy pequeña y se ve muy mal con esa resolución

**Comment by facundobatista** [comment]
Está genial!
